name: update-readme-and-deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write # リポジトリへの書き込み権限
  pages: write    # GitHub Pagesへのデプロイ権限
  id-token: write # IDトークンの作成権限（デプロイ時に必要）

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Update README.md
        run: |
          python update_readme.py

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update README.md automatically"
          git push origin main

      # アーティファクトをアップロードするステップを追加
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: '.' # デプロイ対象のディレクトリ（ルートディレクトリ）

  deploy:
    runs-on: ubuntu-latest
    needs: update-readme # update-readmeジョブが完了した後に実行されるよう設定
    environment:
      name: github-pages # 必須項目
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4.0.0
