name: directory-listing

on: [push]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  pages-directory-listing:
    runs-on: ubuntu-latest
    name: Directory Listings Index
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Directory Listings
        uses: jayanta525/github-pages-directory-listing@v4.0.0
        with:
          FOLDER: . # インデックスを生成するディレクトリ

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: '.' # 生成されたフォルダをアップロード

  deploy:
    runs-on: ubuntu-latest
    needs: pages-directory-listing
    environment:
      name: github-pages # 必須項目
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4.0.0
